import { test, expect } from '@playwright/test';

test('Create new operation FCL', async ({ page }) => {
  await page.goto('https://qa-dora.tibagroup.com/');
  await expect(page.getByText('Sign In Sign in as an')).toBeVisible();
  await expect(page.getByRole('link', { name: 'Sign in as external.' })).toBeVisible();
  await page.getByRole('link', { name: 'Sign in as external.' }).click();
  await page.getByLabel('Username').click();
  await page.getByLabel('Username').fill('testspc@iti.es');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('Qazwer.11');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await expect(page.getByRole('heading', { name: 'Operations' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'New Operation' })).toBeVisible();
  await page.getByRole('button', { name: 'New Operation' }).click();
  await expect(page.getByRole('heading', { name: 'New operation' })).toBeVisible();
  await page.locator('mat-form-field').filter({ hasText: 'SelectSelect *' }).locator('svg').click();
  await page.getByText('CIF Cost,Insurance and Freight').click();
  await page.getByPlaceholder('Search origin', { exact: true }).click();
  await page.getByPlaceholder('Search origin', { exact: true }).fill('Alcan');
  await page.getByText('ESACAAlcanarSpain').click();
  await page.getByPlaceholder('Search destination', { exact: true }).click();
  await page.getByPlaceholder('Search destination', { exact: true }).fill('Palm');
  await page.getByRole('option', { name: 'Las Palmas de Gran Canaria' }).click();
  await page.getByRole('button', { name: 'Apply Ctrl⏎' }).click();
  await expect(page.getByText('Purchased services')).toBeVisible();
  await expect(page.getByRole('button', { name: 'Create operation Ctrl⏎' })).toBeVisible();
  await page.getByRole('button', { name: 'Create operation Ctrl⏎' }).click();
  await expect(page.locator('snack-bar-container')).toBeVisible();
});

test('Create new operation LCL', async ({ page }) => {
  await page.goto('https://qa-dora.tibagroup.com/');
  await expect(page.getByText('Sign In').first()).toBeVisible();
  await expect(page.getByRole('link', { name: 'Sign in as external.' })).toBeVisible();
  await page.getByRole('link', { name: 'Sign in as external.' }).click();
  await expect(page.getByText('Sign In Sign in as an')).toBeVisible();
  await page.getByLabel('Username').click();
  await page.getByLabel('Username').fill('testspc@iti.es');
  await page.getByLabel('Username').press('Tab');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('Qazwer.11');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await expect(page.getByRole('heading', { name: 'Operations' })).toBeVisible();
  await expect(page.getByRole('button', { name: 'New Operation' })).toBeVisible();
  await page.getByRole('button', { name: 'New Operation' }).click();
  await expect(page.locator('app-new-operation-aside div').filter({ hasText: 'Ocean LCL' }).nth(2)).toBeVisible();
  await page.locator('app-new-operation-aside div').filter({ hasText: 'Ocean LCL' }).nth(2).click();
  await page.locator('#mat-select-value-7').click();
  await page.getByText('CIF Cost,Insurance and Freight').click();
  await page.getByPlaceholder('Search origin', { exact: true }).click();
  await page.getByPlaceholder('Search origin', { exact: true }).fill('Alca');
  await page.getByText('ESACAAlcanarSpain').click();
  await page.getByPlaceholder('Search destination', { exact: true }).click();
  await page.getByPlaceholder('Search destination', { exact: true }).fill('Palm');
  await page.getByText('ESPMIPalma de MallorcaSpain').click();
  await page.getByRole('button', { name: 'Apply Ctrl⏎' }).click();
  await page.getByRole('button', { name: 'Create operation Ctrl⏎' }).click();
});

test('Create new operation AIR', async ({ page }) => {
  await page.goto('https://qa-dora.tibagroup.com/');
  await expect(page.getByText('Sign In Sign in as an')).toBeVisible();
  await expect(page.getByRole('link', { name: 'Sign in as external.' })).toBeVisible();
  await page.getByRole('link', { name: 'Sign in as external.' }).click();
  await expect(page.getByText('Sign In Sign in as an')).toBeVisible();
  await page.getByLabel('Username').click();
  await page.getByLabel('Username').fill('testspc@iti.es');
  await page.getByLabel('Password').click();
  await page.getByLabel('Password').fill('Qazwer.11');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await expect(page.getByRole('button', { name: 'New Operation' })).toBeVisible();
  await page.getByRole('button', { name: 'New Operation' }).click();
  await expect(page.locator('app-new-operation-aside div').filter({ hasText: 'Air' }).nth(2)).toBeVisible();
  await page.locator('app-new-operation-aside div').filter({ hasText: 'Air' }).nth(2).click();
  await page.locator('#mat-select-value-7').click();
  await page.getByText('CIP Carriage and Insurance Paid to').click();
  await page.getByPlaceholder('Search origin', { exact: true }).click();
  await page.getByPlaceholder('Search origin', { exact: true }).fill('Madrid');
  await page.getByPlaceholder('Search destination', { exact: true }).click();
  await page.getByPlaceholder('Search destination', { exact: true }).fill('San Pedro');
  await page.getByRole('button', { name: 'Apply Ctrl⏎' }).click();
  await page.getByRole('button', { name: 'Create operation Ctrl⏎' }).click();
  await page.goto('https://qa-dora.tibagroup.com/operations/OP01070815/data');
});